### ISSUE TITLE
displayDialogAsync: dialog content in not loaded from time to time

### ISSUE THREAD

**Issue by ndeeH** [OfficeDev/Office-Add-in-Dialog-API-Simple-Example#6] opened 2017-09-26 08:27 UTC
In a simple scenario we open a static HTML page in an dialog from a ribbon button.
Commands.html is our function file which is called through a ExecuteFunction action:
```
function ExecFunction(event)
    {
        openDialog("ShowTaskPaneHelp.html");
        event.completed();
    }
```

```
function openDialog(relativeUrl)
    {
        if (!Office.context.ui.displayDialogAsync)
            return;

        var location = window.location.href.substring(0, window.location.href.indexOf("Commands.html"));
        console.log("opening dialog at: " + location + relativeUrl);
        Office.context.ui.displayDialogAsync(location + relativeUrl,
            { height: 30, width: 35 }, dialogCallback);
   }
```
Remarks: The dialogCallback is the same code as in your sample.

Sporadically the dialog content does not show up correct (seems the loading panel is stuck!?)
![image](https://user-images.githubusercontent.com/11518242/30849356-597aba8e-a2a2-11e7-92fd-8ab9f468f1b7.png)

The dialogCallback does not show up any errors.
When I resize the window the correct dialog content shows up!?

**Comment by ndeeH** [comment] 2017-09-28 12:23
This must be a bug in the office 16 desktop programs. 
In Office Online this works without any problems.
Any ideas?
(Seems the loading panel is not removed... when I resize the dialog it is removed.)

**Comment by ndeeH** [comment] 2017-10-02 06:58
Where is the best place to report errors in office.js / Office?

**Comment by htryggva** [comment] 2017-10-03 12:21
@weird-dreams We also recently started seeing the exact same issue in Outlook 16. It's like the dialog doesn't render the content until we resize it. We've seen the issue on Current Channel and Office Insider. It looks though as if the issue is not present on the Deferred Channel.

Are you seeing this on Outlook as well?

cc: @LezaMax

**Comment by ndeeH** [comment] 2017-10-03 12:29
@htryggva We just tested in Excel 2016 and Word 2016 (latest Desktop releases 16.0.8326.2107).
It seems that it arises on the approx. third opening of a modal dialog!?
The Online Versions do not have this problem.
cc: @LezaMax

**Comment by lindalu-MSFT** [comment] 2019-07-31 23:37
Closing all issues since this repo is being archived and no longer maintained.

**Closed as completed by lindalu-MSFT** 2019-07-31 23:37 UTC
